/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/blogs": {
    /**
     * List all blogs
     * @description List all blogs
     */
    get: operations["listAllBlogs"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Blog: {
      id?: number;
      slug?: string;
      username: string;
      title: string;
      description: string;
      tags: string[];
      /** Format: date-time */
      createdDate: string;
      favoritesCount: number;
    };
  };
  responses: {
    /** @description List all blogs */
    BlogsResponse: {
      content: {
        "application/json": {
          body: components["schemas"]["Blog"][];
          blogCount: number;
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * List all blogs
   * @description List all blogs
   */
  listAllBlogs: {
    responses: {
      200: components["responses"]["BlogsResponse"];
      /** @description Not found */
      404: {
        content: {
          "application/json": {
            /** @example Blog not found */
            message?: string;
          };
        };
      };
    };
  };
}
